knp_paginator:
    page_range: 5                      # Number of page numbers in pagination
    default_options:
        page_name: page                # Parameter name for page number in URL
        sort_field_name: sort          # Parameter name for sorting field in URL
        sort_direction_name: direction # Parameter name for sorting direction in URL
        distinct: true                 # Ensure distinct results, useful when paginating with joins
    template:
        pagination: "@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig" # sliding pagination controls template
        sortable: "@KnpPaginator/Pagination/twitter_bootstrap_v4_font_awesome_sortable_link.html.twig" # sort link template
        filtration: "@KnpPaginator/Pagination/filtration.html.twig" # filters template
