vich_uploader:
    db_driver: orm

    #mappings:
        #accident:
            #uri_prefix: /public/uploads
            #upload_destination: '%kernel.project_dir%/public/public/uploads'
            #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
