# app/config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
