#index:
#    path: /
#    controller: App\Controller\DefaultController::index


reponse_devis_qr_code:
    path: /reponse/devis/{id}/qr-code
    controller: App\Controller\ReponseDevisController::generateQrCode
    methods: ['GET']
